import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { NavbarSimple } from "./components/Navigation";
// import { ThemeProvider } from "@material-tailwind/react";

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const parkinsans = localFont({
  src: "./fonts/Parkinsans-VariableFont_wght.ttf",
  variable: "--font-parkinsans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Gallery",
  description:
    "Generated by a folder with images from google drive. material tailwind and nextjs",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${parkinsans.variable} ${geistMono.variable} antialiased`}
      >
        {" "}
        <NavbarSimple />
        {children}
      </body>
    </html>
  );
}
